[[queue]]
name = "sync.storage.translation"
processor = "synchronization_storage_queue_message_processor"
chunk_size = 1000

[[queue]]
name = "sync.storage.product_abstract"
processor = "synchronization_storage_queue_message_processor"
chunk_size = 1000

[[queue]]
name = "sync.storage.product"
processor = "synchronization_storage_queue_message_processor"
chunk_size = 1000

[[queue]]
name = "sync.search.product"
processor = "synchronization_search_queue_message_processor"
chunk_size = 1000

[[queue]]
name = "sync.search.category"
processor = "synchronization_search_queue_message_processor"
chunk_size = 1000

[[queue]]
name = "sync.search.cms"
processor = "synchronization_search_queue_message_processor"
chunk_size = 1000

[[queue]]
name = "sync.search.return"
processor = "synchronization_search_queue_message_processor"
chunk_size = 1000

[[queue]]
name = "sync.search.merchant"
processor = "synchronization_search_queue_message_processor"
chunk_size = 1000

[[queue]]
name = "publish"
processor = "event_queue_message_processor"
chunk_size = 500